### PR TITLE
Improve web view

### PR DESCRIPTION
**Pull request by vogdb**
- Add pagination (or at least cut off at X jobs)

Improve readability
- Make web view more responsive
- Use more width
- Mobile friendly (use Bootstrap classes)

Improve details
- Use pulsar task name as entry header
- Add created at and duration fields

### CODE REVIEW

**Comment by vogdb** [comment]
[15:56] Tomasz Durka: let's be heavily influenced by https://travis-ci.org/cargomedia/CM/
		List of jobs can be really short and robust as in this link
		then single job view can contain details and console output
[15:57] Tomasz Durka: I think we need to add couple of additional data pieces like "createdAt", "finishedAt" or some kind of corresponding events collection
[15:59] Aleksei Sanin: Do you still have a call? 
[15:57] Tomasz Durka: not anyumore

**Comment by vogdb** [comment]
@tomaszdurka I think this milestone can be released. wdyt? Please look how it looks to you.

**Comment by tomaszdurka** [comment]
Ok, I will checkout your code and manual test it! :)

**Comment by vogdb** [comment]
You can postpone it for now. I think I forgot to implement auto-update of interface with newly created jobs.

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Wdyt about adding fixutres for easier web-app development?

**Comment by tomaszdurka** [comment]
As discussed with Aleksei, he will add fixtures (script to load predefined data) for easier manual testing.

**Comment by vogdb** [comment]
Fixtures are ready.
You can setup them by running in the root of PRA:
```
npm run-script test-data-fixture
```
It will use `test/data/config.yaml` and fill the database that is declared in this config.

@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Hmm - looks ok :)

But...

I actually thought about sometihng like this https://travis-ci.org/cargomedia/pulsar-rest-api/builds for the list of builds, but left sidebar might be ok too. It's a bit unclear which build is active though.

Another thing is that it's quite colorfull. Also color is the same thing as status is. Maybe combine those two?
Also for the main item progress bar is huge and it is actually never used as progress bar (but rather as flag).

Sidebar cannot scroll all the way down.

**Comment by tomaszdurka** [comment]
Another thing is we are missing some readme about running pulsar-rest-api to develop app locally. We point to npm install -g, although you should run local `bin/pulsar-rest-api`.
Another thing is newly created fixtures does not work with basic config.yml - they put data into different mongo db. 
Yet another thing, but maybe not crucial is that you need local mongo, but maybe I can sort that out in different pull-request using vagrant and docker.

I would propose to add some task manager (or use npm) to start development server (maybe with mongo included), add fixtures, etc.

Wdyt @vogdb ?

**Comment by vogdb** [comment]
> Another thing is that it's quite colorfull. Also color is the same thing as status is. Maybe combine those two?
Also for the main item progress bar is huge and it is actually never used as progress bar (but rather as flag).

Fixed.

> Sidebar cannot scroll all the way down.

Only last 10 jobs are loaded. We can live with that now. Lets create a full enabled pagination in the next PR.

> General running notes

Agree but it's a separate PR again.

@tomaszdurka please review.

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by vogdb** [comment]
paired with @tomaszdurka

**Comment by vogdb** [comment]
@tomaszdurka paired here

**Pull request merged**
