### PR TITLE
Resolve spec failures

### PR DESCRIPTION
**Pull request by vogdb**
https://travis-ci.org/cargomedia/pulsar-rest-api/builds/63663125

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Let's say it's good.

**Comment by tomaszdurka** [comment]
TODO: Investigate if this is actually because of our tests nature (nested process).

**Comment by vogdb** [comment]
@tomaszdurka 
That happened because in `Pulsar.prototype._shutdown` we manually killed jobs.
```js
  Pulsar.prototype._shutdown = function(signal) {
    ...
    _.each(this.jobQueue, function(job) {
      job.kill();
    })
```
So, this `job.kill` killed job, so it didn't receive the signal but only the code.

**Comment by vogdb** [comment]
I think now that is not actual because now we don't kill jobs on shutdown #78.

**Pull request merged**
