### PR TITLE
Cannot read property 'pulsarOptions' of undefined

### PR DESCRIPTION
**Pull request by vogdb**
```
17:50:15 ERROR - Request { url: '/sk/staging', params: {} } caught exception [TypeError: Cannot read property 'pulsarOptions' of undefined]
TypeError: Cannot read property 'pulsarOptions' of undefined
    at module.exports.Pulsar._createJob (/usr/lib/node_modules/pulsar-rest-api/lib/pulsar/index.js:128:17)
    at module.exports.Pulsar.createJob (/usr/lib/node_modules/pulsar-rest-api/lib/pulsar/index.js:63:20)
    at createJob (/usr/lib/node_modules/pulsar-rest-api/lib/pulsar/rest.js:24:19)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/layer.js:82:5)
    at /usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/index.js:234:24
    at param (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/index.js:331:14)
    at param (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/index.js:347:14)
```

cc @tomaszdurka

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please look.

**Comment by njam** [comment]
@tomaszdurka please review

@vogdb build failed

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Looks good!

**Pull request merged**
