### PR TITLE
Add `restart` endpoint to the API. 

### PR DESCRIPTION
**Pull request by vogdb**
To restart the pulsar job.

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Make `Pulsar.restart` throw/fail when status is different than failed/killed rather then silently ignore it.

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Looks good

**Pull request merged**
