### PR TITLE
Upgrade web-app dependencies (fix test runner to exit 1 on failures)

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam Please review. 

Needed for https://github.com/cargomedia/puppet-packages/pull/900

**Comment by njam** [comment]
The travis build shows failing tests, but `npm test` exits with code `0`.
Can you check what's going on?

**Comment by tomaszdurka** [comment]
Indeed, I will take a look.

**Comment by tomaszdurka** [comment]
@njam Can you give me a go here ? I've managed to make tests fail on failure. 

I did not fix the tests though as I've created https://github.com/cargomedia/pulsar-rest-api/issues/80 and asked Aleksei to take care of it.

**Comment by njam** [comment]
Use `_.some()` to return boolean? Rest looks good

**Comment by tomaszdurka** [comment]
I think I've tried that and thought this version is more readible as I still should introduce variable `hasFailures`.

**Comment by tomaszdurka** [comment]
@njam please review.

**Comment by vogdb** [comment]
lgtm!

**Comment by njam** [comment]
lgtm

**Pull request merged**
