### PR TITLE
Remove https restriction from cookie setter.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by vogdb** [comment]
or may be @njam please review?

**Comment by njam** [comment]
`httpOnly` defaults to `true` ([docu](https://github.com/pillarjs/cookies#cookiesset-name--value---options--)). So now it will be `true` and we will not be able to access the cookie from javascript ([docu](http://en.wikipedia.org/wiki/HTTP_cookie#HttpOnly_cookie)) - is this desired?

**Comment by vogdb** [comment]
No! It's just my error as always ='(

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
lgtm!

**Pull request merged**
