### PR TITLE
Improve docu

### PR DESCRIPTION
**Pull request by vogdb**
cc @tomaszdurka 

Some small suggestions for readme:
- Config code block: Links don't work because it's code block. Rather make it a list?
- Docu: Add steps on how to fill out "New Github Application" form
- Question: What needs to be filled in `auth.callbackUrl` (docu unclear)?
- CURL example: 
 - Don't use `-k` (which is to ignore SSL problems)
 - Shorten "put your Github token here, remove curly braces"? -> just `{github-token}`

### CODE REVIEW

**Comment by vogdb** [comment]
@njam or @tomaszdurka please review.

**Comment by njam** [comment]
- In the YAML docu why do you have a dot (`.`) after each item? How about a colon (`:`) ?
- Github OAuth App setup: How about suggesting to leave "Application description" and "Authorization callback URL" empty? It will make setup easier and works too..
- Github OAuth App setup: Don't mention fields twice (intro sentence and then again in the list)

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
lgtm! @tomaszdurka wanna double check?

**Comment by tomaszdurka** [comment]
Looks good.

**Pull request merged**
