### PR TITLE
Release 0.2.0 version.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Ok. I would still call it 0.1.6 :) But it's ok!

**Comment by vogdb** [comment]
I thought about it too but we introduced an incompatibility with `config.pulsar.repo`. So =\.

**Comment by tomaszdurka** [comment]
Let's merge :)

**Pull request merged**
