### PR TITLE
Log: add date

### PR DESCRIPTION
**Pull request by vogdb**
Currently log looks like this:
```
8:20:23 AM INFO - Pulsar API is ready and listening on port 8080
```

@vogdb could you add the date?
cc @tomaszdurka

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka want to review?

**Comment by tomaszdurka** [comment]
lgtm

**Comment by vogdb** [comment]
@njam please use version 0.5.2

**Comment by njam** [comment]
thanks!

**Pull request merged**
