### PR TITLE
Output formatting: Don't wrap lines

### PR DESCRIPTION
**Pull request by vogdb**
@tomaszdurka @vogdb 
For better readability how about letting the output panel scroll in the x-direction instead of wrapping lines?

### CODE REVIEW

**Comment by vogdb** [comment]
I've added `overflow` to PRA Web client but it will not help that much.
@tomaszdurka please participate! =)

**Comment by vogdb** [comment]
Hm. Probable it's achievable after all. Please wait while I'm researching it further.

**Comment by njam** [comment]
We have the desired behaviour in our admin - check out the error log output!

**Comment by vogdb** [comment]
I think these small changes are enough =) @tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Looks good.

**Pull request merged**
